spring:
  datasource:
    url: jdbc:mysql://localhost:3306/QA?useUnicode=true&serverTimezone=UTC
    username: qa_user
    password: test
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true

#    Run lines below just at first database initialization

#    properties:
#      hibernate:
#        hbm2ddl:
#          delimiter: ";"
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: qa.sql